# Generated by Django 4.2.7 on 2025-07-09 12:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)])),
                ('conditions', models.TextField(blank=True, help_text='Specific conditions for the benefit')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Beneficiary Relation',
                'verbose_name_plural': 'Beneficiary Relations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('PROOF_OF_INCOME', 'Proof of Income'), ('PROOF_OF_ADDRESS', 'Proof of Address'), ('POWER_OF_ATTORNEY', 'Power of Attorney'), ('MANAGEMENT_AGREEMENT', 'Management Agreement'), ('ADVISORY_AGREEMENT', 'Advisory Agreement')], max_length=30)),
                ('url', models.URLField(help_text='URL to the document (not uploaded to system)')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document Attachment',
                'verbose_name_plural': 'Document Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('NATURAL_PERSON', 'Natural Person'), ('JURIDICAL_PERSON', 'Juridical Person')], max_length=20)),
                ('name', models.CharField(help_text='Full name', max_length=200)),
                ('is_partner', models.BooleanField(default=False, help_text='Is this party a business partner?')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('tax_identification_number', models.CharField(blank=True, help_text='Tax ID number from fiscal residence country', max_length=50)),
                ('nationality', models.CharField(blank=True, choices=[('BR', 'Brasil'), ('US', 'Estados Unidos'), ('BS', 'Bahamas'), ('KN', 'São Cristóvão e Nevis'), ('VG', 'Ilhas Virgens Britânicas'), ('PA', 'Panamá'), ('CH', 'Suíça'), ('SG', 'Singapura'), ('HK', 'Hong Kong'), ('OTHER', 'Outro')], max_length=10)),
                ('birth_date', models.DateField(blank=True, help_text='Birth date for natural persons, incorporation date for juridical persons', null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Passport number', max_length=50)),
                ('issued_at', models.DateField(help_text='Issue date')),
                ('expires_at', models.DateField(help_text='Expiration date')),
                ('issuing_country', models.CharField(choices=[('BR', 'Brasil'), ('US', 'Estados Unidos'), ('BS', 'Bahamas'), ('KN', 'São Cristóvão e Nevis'), ('VG', 'Ilhas Virgens Britânicas'), ('PA', 'Panamá'), ('CH', 'Suíça'), ('SG', 'Singapura'), ('HK', 'Hong Kong'), ('OTHER', 'Outro')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='parties.party')),
            ],
            options={
                'verbose_name': 'Passport',
                'verbose_name_plural': 'Passports',
                'ordering': ['-expires_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('MANAGER', 'Manager'), ('HOLDER', 'Holder'), ('ULTIMATE_BENEFICIAL_OWNER', 'Ultimate Beneficial Owner'), ('BENEFICIARY', 'Beneficiary'), ('SETTLOR', 'Settlor'), ('PROTECTOR', 'Protector'), ('ATTORNEY', 'Attorney'), ('ADVISOR', 'Advisor'), ('TRUSTEE', 'Trustee'), ('CUSTODIAN', 'Custodian')], max_length=30)),
                ('context', models.CharField(blank=True, help_text='Context where this role applies', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='parties.party')),
            ],
            options={
                'verbose_name': 'Party Role',
                'verbose_name_plural': 'Party Roles',
            },
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['person_type'], name='parties_par_person__6e7a98_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['tax_identification_number'], name='parties_par_tax_ide_64e689_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['nationality'], name='parties_par_nationa_639f15_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['active'], name='parties_par_active_b5a235_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['is_partner'], name='parties_par_is_part_17e27e_idx'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parties.party'),
        ),
        migrations.AddField(
            model_name='beneficiaryrelation',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_benefits', to='parties.party'),
        ),
        migrations.AddField(
            model_name='beneficiaryrelation',
            name='giver_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_benefits', to='corporate.entity'),
        ),
        migrations.AddField(
            model_name='beneficiaryrelation',
            name='giver_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_benefits', to='parties.party'),
        ),
        migrations.AddIndex(
            model_name='passport',
            index=models.Index(fields=['party'], name='parties_pas_party_i_ec7dca_idx'),
        ),
        migrations.AddIndex(
            model_name='passport',
            index=models.Index(fields=['expires_at'], name='parties_pas_expires_c5434f_idx'),
        ),
        migrations.AddIndex(
            model_name='passport',
            index=models.Index(fields=['active'], name='parties_pas_active_a705ab_idx'),
        ),
        migrations.AddIndex(
            model_name='partyrole',
            index=models.Index(fields=['party'], name='parties_par_party_i_bec464_idx'),
        ),
        migrations.AddIndex(
            model_name='partyrole',
            index=models.Index(fields=['role_type'], name='parties_par_role_ty_7591a1_idx'),
        ),
        migrations.AddIndex(
            model_name='partyrole',
            index=models.Index(fields=['active'], name='parties_par_active_21451b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partyrole',
            unique_together={('party', 'role_type', 'context')},
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['party'], name='parties_doc_party_i_282b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['document_type'], name='parties_doc_documen_1f7687_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['active'], name='parties_doc_active_b90258_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiaryrelation',
            index=models.Index(fields=['giver_party'], name='parties_ben_giver_p_07e309_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiaryrelation',
            index=models.Index(fields=['giver_entity'], name='parties_ben_giver_e_7ee446_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiaryrelation',
            index=models.Index(fields=['beneficiary'], name='parties_ben_benefic_f9d35e_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiaryrelation',
            index=models.Index(fields=['active'], name='parties_ben_active_e7e08f_idx'),
        ),
    ]
