# Generated by Django 4.2.7 on 2025-07-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporate_relationship', '0001_initial'),
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdictionalert',
            name='service_connection',
            field=models.ForeignKey(blank=True, help_text='Associated service for this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporate_relationship.service'),
        ),
        migrations.AlterUniqueTogether(
            name='validationrule',
            unique_together={('estrutura_a', 'estrutura_b', 'tipo_relacionamento')},
        ),
        migrations.AddIndex(
            model_name='successor',
            index=models.Index(fields=['ubo_proprietario', 'ativo'], name='corporate_s_ubo_pro_0d1a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='successor',
            index=models.Index(fields=['data_efetivacao'], name='corporate_s_data_ef_673ee8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='successor',
            unique_together={('ubo_proprietario', 'ubo_sucessor')},
        ),
        migrations.AlterUniqueTogether(
            name='structureownership',
            unique_together={('parent', 'child')},
        ),
        migrations.AddIndex(
            model_name='jurisdictionalert',
            index=models.Index(fields=['jurisdicao', 'tipo_alerta'], name='corporate_j_jurisdi_06c724_idx'),
        ),
        migrations.AddIndex(
            model_name='jurisdictionalert',
            index=models.Index(fields=['next_deadline'], name='corporate_j_next_de_9674b2_idx'),
        ),
        migrations.AddIndex(
            model_name='jurisdictionalert',
            index=models.Index(fields=['deadline_type'], name='corporate_j_deadlin_06399b_idx'),
        ),
        migrations.AddIndex(
            model_name='jurisdictionalert',
            index=models.Index(fields=['prioridade'], name='corporate_j_priorid_0c94b8_idx'),
        ),
        migrations.AddIndex(
            model_name='jurisdictionalert',
            index=models.Index(fields=['ativo'], name='corporate_j_ativo_46580c_idx'),
        ),
    ]
