# Generated by Django 4.2.7 on 2025-07-07 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='associated_product',
            field=models.ForeignKey(blank=True, help_text='Product this service is associated with (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.product'),
        ),
        migrations.AddField(
            model_name='service',
            name='associated_structure',
            field=models.ForeignKey(blank=True, help_text='Legal Structure this service is associated with (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='corporate.structure'),
        ),
        migrations.AddField(
            model_name='jurisdictionalert',
            name='estruturas_aplicaveis',
            field=models.ManyToManyField(blank=True, help_text='Structures to which this alert applies', to='corporate.structure'),
        ),
        migrations.AddField(
            model_name='jurisdictionalert',
            name='service_connection',
            field=models.ForeignKey(blank=True, help_text='Associated service for this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporate.service'),
        ),
        migrations.AddField(
            model_name='jurisdictionalert',
            name='ubos_aplicaveis',
            field=models.ManyToManyField(blank=True, help_text='UBOs to which this alert applies', to='corporate.ubo'),
        ),
        migrations.AlterUniqueTogether(
            name='validationrule',
            unique_together={('estrutura_a', 'estrutura_b', 'tipo_relacionamento')},
        ),
        migrations.AddIndex(
            model_name='successor',
            index=models.Index(fields=['ubo_proprietario', 'ativo'], name='corporate_s_ubo_pro_0d1a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='successor',
            index=models.Index(fields=['data_efetivacao'], name='corporate_s_data_ef_673ee8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='successor',
            unique_together={('ubo_proprietario', 'ubo_sucessor')},
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['jurisdicao'], name='corporate_s_jurisdi_3caab2_idx'),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['ativo'], name='corporate_s_ativo_fec972_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['service', 'status'], name='corporate_s_service_723563_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['start_date'], name='corporate_s_start_d_68ca3e_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['due_date'], name='corporate_s_due_dat_acf9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['status'], name='corporate_s_status_ea18db_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['priority'], name='corporate_s_priorit_d10f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['responsible_person'], name='corporate_s_respons_39836c_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_type'], name='corporate_s_service_257085_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status'], name='corporate_s_status_a7ed5c_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['associated_product'], name='corporate_s_associa_630fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['associated_structure'], name='corporate_s_associa_cdf5da_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['ativo'], name='corporate_s_ativo_868a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='jurisdictionalert',
            index=models.Index(fields=['jurisdicao', 'tipo_alerta'], name='corporate_j_jurisdi_06c724_idx'),
        ),
        migrations.AddIndex(
            model_name='jurisdictionalert',
            index=models.Index(fields=['next_deadline'], name='corporate_j_next_de_9674b2_idx'),
        ),
        migrations.AddIndex(
            model_name='jurisdictionalert',
            index=models.Index(fields=['deadline_type'], name='corporate_j_deadlin_06399b_idx'),
        ),
        migrations.AddIndex(
            model_name='jurisdictionalert',
            index=models.Index(fields=['prioridade'], name='corporate_j_priorid_0c94b8_idx'),
        ),
        migrations.AddIndex(
            model_name='jurisdictionalert',
            index=models.Index(fields=['ativo'], name='corporate_j_ativo_46580c_idx'),
        ),
    ]
