# Generated by Django 4.2.7 on 2025-07-09 17:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
        ('corporate', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(help_text="Custom name for this entity instance (e.g. 'João's Wyoming LLC')", max_length=200)),
                ('total_shares', models.PositiveIntegerField(blank=True, help_text='Number of shares for this specific instance', null=True)),
                ('corporate_name', models.CharField(blank=True, help_text='Corporate name when entity is used in this structure', max_length=200)),
                ('hash_number', models.CharField(blank=True, help_text='Hash number when entity is used in this structure', max_length=50)),
                ('level', models.PositiveIntegerField(default=1, help_text='Level in the structure hierarchy (1 = top level)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_template', models.ForeignKey(help_text='The entity template this node is based on', on_delete=django.db.models.deletion.CASCADE, to='corporate.entity')),
                ('parent_node', models.ForeignKey(blank=True, help_text='Parent node in the structure hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_nodes', to='corporate.structurenode')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='corporate.structure')),
            ],
            options={
                'verbose_name': 'Structure Node',
                'verbose_name_plural': 'Structure Nodes',
            },
        ),
        migrations.CreateModel(
            name='NodeOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(decimal_places=2, help_text='Ownership percentage (0.01 to 100.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)])),
                ('owned_shares', models.PositiveIntegerField(blank=True, help_text='Number of shares owned', null=True)),
                ('share_value_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Value per share in USD', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('total_value_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Total value of owned shares in USD', max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owned_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_received', to='corporate.structurenode')),
                ('owner_node', models.ForeignKey(blank=True, help_text='Structure node owner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_ownerships', to='corporate.structurenode')),
                ('owner_party', models.ForeignKey(blank=True, help_text='Party (UBO) owner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_nodes', to='parties.party')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_ownerships', to='corporate.structure')),
            ],
            options={
                'verbose_name': 'Node Ownership',
                'verbose_name_plural': 'Node Ownerships',
            },
        ),
        migrations.AddIndex(
            model_name='structurenode',
            index=models.Index(fields=['structure', 'level'], name='corporate_s_structu_b1b1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='structurenode',
            index=models.Index(fields=['entity_template'], name='corporate_s_entity__8c396d_idx'),
        ),
        migrations.AddIndex(
            model_name='structurenode',
            index=models.Index(fields=['parent_node'], name='corporate_s_parent__441d17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='structurenode',
            unique_together={('structure', 'custom_name')},
        ),
        migrations.AddIndex(
            model_name='nodeownership',
            index=models.Index(fields=['structure'], name='corporate_n_structu_f34acb_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeownership',
            index=models.Index(fields=['owner_party'], name='corporate_n_owner_p_23ff99_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeownership',
            index=models.Index(fields=['owner_node'], name='corporate_n_owner_n_2fd7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeownership',
            index=models.Index(fields=['owned_node'], name='corporate_n_owned_n_d363ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeownership',
            unique_together={('structure', 'owner_party', 'owner_node', 'owned_node')},
        ),
    ]
