# Generated by Django 4.2.7 on 2025-07-07 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['nome'], 'verbose_name': 'Legal Structure', 'verbose_name_plural': 'Legal Structures'},
        ),
        migrations.AddField(
            model_name='structure',
            name='complexidade',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=3, help_text='Complexity level from 1 (simple) to 5 (very complex)'),
        ),
        migrations.AddField(
            model_name='structure',
            name='documentacao_necessaria',
            field=models.TextField(default='Standard documentation required', help_text='Required documentation for setup'),
        ),
        migrations.AddField(
            model_name='structure',
            name='facilidade_banking',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=3, help_text='Banking facility level from 1 (difficult) to 5 (very easy)'),
        ),
        migrations.AddField(
            model_name='structure',
            name='formularios_obrigatorios_brasil',
            field=models.TextField(blank=True, help_text='Required Brazilian forms and reporting obligations'),
        ),
        migrations.AddField(
            model_name='structure',
            name='formularios_obrigatorios_eua',
            field=models.TextField(blank=True, help_text='Required US forms and reporting obligations'),
        ),
        migrations.AddField(
            model_name='structure',
            name='impacto_privacidade',
            field=models.TextField(default='Standard privacy protections apply', help_text='Detailed privacy implications and protections'),
        ),
        migrations.AddField(
            model_name='structure',
            name='impacto_tributario_brasil',
            field=models.TextField(default='To be determined', help_text='Detailed tax implications in Brazil'),
        ),
        migrations.AddField(
            model_name='structure',
            name='impacto_tributario_eua',
            field=models.TextField(default='To be determined', help_text='Detailed tax implications in the United States'),
        ),
        migrations.AddField(
            model_name='structure',
            name='impacto_tributario_outros',
            field=models.TextField(blank=True, help_text='Tax implications in other jurisdictions'),
        ),
        migrations.AddField(
            model_name='structure',
            name='nivel_confidencialidade',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=3, help_text='Confidentiality level from 1 (low) to 5 (very high)'),
        ),
        migrations.AddField(
            model_name='structure',
            name='protecao_patrimonial',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=3, help_text='Asset protection level from 1 (low) to 5 (very high)'),
        ),
        migrations.AddField(
            model_name='structure',
            name='tipo',
            field=models.CharField(choices=[('TRUST', 'Trust'), ('FOREIGN_TRUST', 'Foreign Trust'), ('FUND', 'Fund'), ('IBC', 'International Business Company'), ('LLC_DISREGARDED', 'LLC Disregarded Entity'), ('LLC_PARTNERSHIP', 'LLC Partnership'), ('LLC_AS_CORP', 'LLC as a Corp'), ('CORP', 'Corp'), ('WYOMING_FOUNDATION', 'Wyoming Statutory Foundation')], default='CORP', help_text='Structure type', max_length=50),
        ),
        migrations.AddField(
            model_name='structure',
            name='url_documentos',
            field=models.URLField(blank=True, help_text='URL for structure documents and templates'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Whether structure is active'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='compliance_score',
            field=models.IntegerField(blank=True, help_text='Compliance score from 0 to 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='structure',
            name='documentos_necessarios',
            field=models.TextField(blank=True, help_text='Additional required documents for setup (legacy field)'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='privacidade_score',
            field=models.IntegerField(blank=True, help_text='Privacy score from 0 to 100 (calculated from nivel_confidencialidade)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='structure',
            name='tempo_implementacao',
            field=models.IntegerField(default=30, help_text='Implementation time in days', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['tipo'], name='corporate_s_tipo_15aa3e_idx'),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['complexidade'], name='corporate_s_complex_842c0d_idx'),
        ),
    ]
