# Generated by Django 4.2.7 on 2025-07-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jurisdictionalert",
            name="custom_recurrence_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Custom configuration for complex recurrence patterns",
            ),
        ),
    ]
