# Generated by Django 4.2.7 on 2025-07-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_add_structure_nodes_and_improve_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='banking_relation_score',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='compliance_score',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='documents_url',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='implementation_templates',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='privacy_score',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='required_documentation',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='required_forms_brazil',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='required_forms_usa',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='tax_impact_others',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='total_shares',
        ),
        migrations.AddField(
            model_name='entity',
            name='implementation_documents',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field storing document templates (Operating Agreement, Memorandum, etc.)'),
        ),
        migrations.AddField(
            model_name='entity',
            name='legal_requirements',
            field=models.TextField(blank=True, help_text="Legal obligations, form submissions, and compliance requirements in the entity's jurisdiction"),
        ),
        migrations.AddField(
            model_name='entity',
            name='required_documents',
            field=models.TextField(default='Standard documentation required', help_text='Required documents for setup (Passport, Proof of address, etc.)'),
        ),
        migrations.AddField(
            model_name='entity',
            name='tax_impact_local',
            field=models.TextField(default='To be determined', help_text="Tax implications in the entity's jurisdiction"),
        ),
        migrations.AlterField(
            model_name='entity',
            name='tax_impact_brazil',
            field=models.TextField(default='To be determined', help_text='Tax implications in Brazil (if applicable)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='tax_impact_usa',
            field=models.TextField(default='To be determined', help_text='Tax implications in USA (if applicable)'),
        ),
    ]
