# Generated by Django 4.2.7 on 2025-07-09 13:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporate_relationship', '0001_initial'),
        ('corporate', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(choices=[('USD', 'US Dollar'), ('BRL', 'Brazilian Real'), ('EUR', 'Euro')], max_length=3)),
                ('markup_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], max_length=10)),
                ('markup_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corporate.entity')),
            ],
            options={
                'verbose_name': 'Entity Price',
                'verbose_name_plural': 'Entity Prices',
            },
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(choices=[('USD', 'US Dollar'), ('BRL', 'Brazilian Real'), ('EUR', 'Euro')], max_length=3)),
                ('markup_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], max_length=10)),
                ('markup_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='corporate_relationship.service')),
            ],
            options={
                'verbose_name': 'Service Price',
                'verbose_name_plural': 'Service Prices',
            },
        ),
        migrations.CreateModel(
            name='ServiceCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost_type', models.CharField(choices=[('LEGAL_FEE', 'Legal Fee'), ('SERVICE_PROVIDER', 'Service Provider')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='financial_department.serviceprice')),
            ],
            options={
                'verbose_name': 'Service Cost',
                'verbose_name_plural': 'Service Costs',
                'ordering': ['service_price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IncorporationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cost component name', max_length=200)),
                ('cost_type', models.CharField(choices=[('LEGAL_FEE', 'Legal Fee'), ('SERVICE_PROVIDER', 'Service Provider')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='financial_department.entityprice')),
            ],
            options={
                'verbose_name': 'Incorporation Cost',
                'verbose_name_plural': 'Incorporation Costs',
                'ordering': ['entity_price', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='serviceprice',
            index=models.Index(fields=['service'], name='financial_d_service_7b4a46_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprice',
            index=models.Index(fields=['base_currency'], name='financial_d_base_cu_4a5947_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecost',
            index=models.Index(fields=['service_price'], name='financial_d_service_0cee93_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecost',
            index=models.Index(fields=['cost_type'], name='financial_d_cost_ty_60654a_idx'),
        ),
        migrations.AddIndex(
            model_name='incorporationcost',
            index=models.Index(fields=['entity_price'], name='financial_d_entity__19e5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='incorporationcost',
            index=models.Index(fields=['cost_type'], name='financial_d_cost_ty_f6a0f2_idx'),
        ),
        migrations.AddIndex(
            model_name='entityprice',
            index=models.Index(fields=['entity'], name='financial_d_entity__4beb9c_idx'),
        ),
        migrations.AddIndex(
            model_name='entityprice',
            index=models.Index(fields=['base_currency'], name='financial_d_base_cu_99e700_idx'),
        ),
    ]
