# Generated by Django 4.2.7 on 2025-07-07 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Structure name', max_length=100)),
                ('tipo', models.CharField(choices=[('TRUST', 'Trust'), ('FOREIGN_TRUST', 'Foreign Trust'), ('FUND', 'Fund'), ('IBC', 'International Business Company'), ('LLC_DISREGARDED', 'LLC Disregarded Entity'), ('LLC_PARTNERSHIP', 'LLC Partnership'), ('LLC_AS_CORP', 'LLC as a Corp'), ('CORP', 'Corp'), ('WYOMING_FOUNDATION', 'Wyoming Statutory Foundation')], help_text='Structure type', max_length=50)),
                ('descricao', models.TextField(help_text='Detailed description of the structure')),
                ('jurisdicao', models.CharField(choices=[('US', 'United States'), ('BS', 'Bahamas'), ('BR', 'Brazil'), ('BZ', 'Belize'), ('VG', 'British Virgin Islands'), ('KY', 'Cayman Islands'), ('PA', 'Panama')], default='US', help_text='Primary jurisdiction', max_length=10)),
                ('estado_us', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia')], help_text='US State (only if jurisdiction is United States)', max_length=10, null=True)),
                ('estado_br', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Brazilian State (only if jurisdiction is Brazil)', max_length=10, null=True)),
                ('custo_base', models.DecimalField(decimal_places=2, help_text='Base setup cost in USD', max_digits=10)),
                ('custo_manutencao', models.DecimalField(decimal_places=2, help_text='Annual maintenance cost in USD', max_digits=10)),
                ('tempo_implementacao', models.IntegerField(help_text='Implementation time in days', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('complexidade', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], help_text='Complexity level from 1 (simple) to 5 (very complex)')),
                ('impacto_tributario_eua', models.TextField(help_text='Detailed tax implications in the United States')),
                ('impacto_tributario_brasil', models.TextField(help_text='Detailed tax implications in Brazil')),
                ('impacto_tributario_outros', models.TextField(blank=True, help_text='Tax implications in other jurisdictions')),
                ('nivel_confidencialidade', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], help_text='Confidentiality level from 1 (low) to 5 (very high)')),
                ('protecao_patrimonial', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], help_text='Asset protection level from 1 (low) to 5 (very high)')),
                ('impacto_privacidade', models.TextField(help_text='Detailed privacy implications and protections')),
                ('facilidade_banking', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], help_text='Banking facility level from 1 (difficult) to 5 (very easy)')),
                ('documentacao_necessaria', models.TextField(help_text='Required documentation for setup')),
                ('url_documentos', models.URLField(blank=True, help_text='URL for structure documents and templates')),
                ('formularios_obrigatorios_eua', models.TextField(blank=True, help_text='Required US forms and reporting obligations')),
                ('formularios_obrigatorios_brasil', models.TextField(blank=True, help_text='Required Brazilian forms and reporting obligations')),
                ('ativo', models.BooleanField(default=True, help_text='Whether structure is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Structure',
                'verbose_name_plural': 'Legal Structures',
                'ordering': ['nome'],
            },
        ),
    ]
