# Generated by Django 4.2.7 on 2025-07-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_alter_structure_options_structure_complexidade_and_more'),
        ('estruturas_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estrutura',
        ),
        migrations.CreateModel(
            name='Estrutura',
            fields=[
            ],
            options={
                'verbose_name': 'Legal Structure (Legacy)',
                'verbose_name_plural': 'Legal Structures (Legacy)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('corporate.structure',),
        ),
    ]
