# Generated by Django 4.2.7 on 2025-07-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estruturas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Nome completo do Ultimate Beneficial Owner', max_length=200)),
                ('data_nascimento', models.DateField(help_text='Data de nascimento')),
                ('nacionalidade', models.CharField(choices=[('BR', 'Brasil'), ('US', 'Estados Unidos'), ('BS', 'Bahamas'), ('KN', 'São Cristóvão e Nevis'), ('VG', 'Ilhas Virgens Britânicas'), ('PA', 'Panamá'), ('CH', 'Suíça'), ('SG', 'Singapura'), ('HK', 'Hong Kong'), ('OTHER', 'Outro')], help_text='Nacionalidade do UBO', max_length=10)),
                ('tin', models.CharField(help_text='Tax Identification Number - número emitido pelo país de residência fiscal', max_length=50)),
                ('endereco_residencia_fiscal', models.TextField(blank=True, help_text='Endereço completo de residência fiscal')),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email de contato', max_length=254)),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre o UBO')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ultimate Beneficial Owner',
                'verbose_name_plural': 'Ultimate Beneficial Owners',
                'ordering': ['nome_completo'],
                'indexes': [models.Index(fields=['tin'], name='estruturas__tin_3668d4_idx'), models.Index(fields=['nacionalidade'], name='estruturas__naciona_54c8c0_idx'), models.Index(fields=['ativo'], name='estruturas__ativo_b8768f_idx')],
            },
        ),
    ]
