# Generated by Django 4.2.7 on 2025-07-06 21:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estruturas_app', '0002_ubo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Successor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Percentual que o sucessor receberá (0.01 a 100.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)])),
                ('data_definicao', models.DateTimeField(auto_now_add=True, help_text='Data em que a sucessão foi definida')),
                ('data_efetivacao', models.DateField(blank=True, help_text='Data em que a sucessão deve ser efetivada (opcional)', null=True)),
                ('condicoes', models.TextField(blank=True, help_text='Condições específicas para a sucessão')),
                ('ativo', models.BooleanField(default=True)),
                ('efetivado', models.BooleanField(default=False)),
                ('data_efetivacao_real', models.DateTimeField(blank=True, help_text='Data real em que a sucessão foi efetivada', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ubo_proprietario', models.ForeignKey(help_text='UBO que está definindo a sucessão', on_delete=django.db.models.deletion.CASCADE, related_name='sucessores_definidos', to='estruturas_app.ubo')),
                ('ubo_sucessor', models.ForeignKey(help_text='UBO que receberá a sucessão', on_delete=django.db.models.deletion.CASCADE, related_name='sucessoes_recebidas', to='estruturas_app.ubo')),
            ],
            options={
                'verbose_name': 'Successor',
                'verbose_name_plural': 'Successors',
                'ordering': ['-data_definicao'],
                'indexes': [models.Index(fields=['ubo_proprietario', 'ativo'], name='estruturas__ubo_pro_0a2af9_idx'), models.Index(fields=['data_efetivacao'], name='estruturas__data_ef_0922e5_idx')],
                'unique_together': {('ubo_proprietario', 'ubo_sucessor')},
            },
        ),
    ]
