# Generated by Django 4.2.7 on 2025-07-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estruturas_app', '0003_successor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto', max_length=100)),
                ('categoria', models.CharField(choices=[('TECH', 'Technology'), ('REAL_ESTATE', 'Real Estate'), ('TRADING', 'Trading'), ('FAMILY_OFFICE', 'Family Office'), ('INVESTMENT', 'Investment'), ('GENERAL', 'General')], help_text='Categoria do produto', max_length=20)),
                ('complexidade_template', models.CharField(choices=[('BASIC', 'Basic Configuration'), ('INTERMEDIATE', 'Intermediate Configuration'), ('ADVANCED', 'Advanced Configuration'), ('EXPERT', 'Expert Configuration')], default='BASIC', help_text='Nível de complexidade', max_length=20)),
                ('descricao', models.TextField(help_text='Descrição detalhada do produto')),
                ('commercial_name', models.CharField(help_text='Nome comercial do produto (texto livre)', max_length=200)),
                ('master_agreement_url', models.URLField(help_text='URL para documento de Master Agreement')),
                ('configuracao', models.JSONField(help_text='Configuração completa do produto em JSON')),
                ('custo_automatico', models.BooleanField(default=True, help_text='Se True, custo é calculado automaticamente das estruturas')),
                ('custo_manual', models.DecimalField(blank=True, decimal_places=2, help_text='Custo manual (usado quando custo_automatico=False)', max_digits=12, null=True)),
                ('tempo_total_implementacao', models.IntegerField(help_text='Tempo total de implementação em dias')),
                ('uso_count', models.IntegerField(default=0, help_text='Número de vezes que este produto foi usado')),
                ('publico_alvo', models.TextField(blank=True, help_text='Público-alvo do produto')),
                ('casos_uso', models.TextField(blank=True, help_text='Casos de uso comuns')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-uso_count', 'commercial_name'],
                'indexes': [models.Index(fields=['commercial_name'], name='estruturas__commerc_c58c8d_idx'), models.Index(fields=['categoria'], name='estruturas__categor_02fd1e_idx'), models.Index(fields=['ativo'], name='estruturas__ativo_fecd52_idx')],
            },
        ),
    ]
