# Generated by Django 4.2.7 on 2025-07-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estruturas_app', '0005_personalizedproduct_personalizedproductubo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Name of the service', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the service')),
                ('service_type', models.CharField(choices=[('LEGAL', 'Legal'), ('TAX', 'Tax'), ('COMPLIANCE', 'Compliance'), ('ADMINISTRATIVE', 'Administrative'), ('CONSULTING', 'Consulting'), ('FORMATION', 'Formation'), ('MAINTENANCE', 'Maintenance')], help_text='Type of service provided', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of the service (optional)', max_digits=12, null=True)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated duration in days', null=True)),
                ('requirements', models.JSONField(default=dict, help_text='Service requirements and prerequisites')),
                ('deliverables', models.JSONField(default=dict, help_text='Expected deliverables and outcomes')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Current status of the service', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['service_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_description', models.TextField(help_text='Detailed description of the activity')),
                ('activity_title', models.CharField(help_text='Short title for the activity', max_length=200)),
                ('start_date', models.DateField(help_text='Planned or actual start date')),
                ('completion_date', models.DateField(blank=True, help_text='Actual completion date (optional)', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Due date for completion (optional)', null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='PLANNED', help_text='Current status of the activity', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Priority level of the activity', max_length=10)),
                ('responsible_person', models.CharField(help_text='Person responsible for this activity', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes and observations')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours for completion', max_digits=8, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Actual hours spent', max_digits=8, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Activity',
                'verbose_name_plural': 'Service Activities',
                'ordering': ['-start_date', 'priority'],
            },
        ),
        migrations.AlterModelOptions(
            name='alertajurisdicao',
            options={'ordering': ['-prioridade', 'next_deadline', 'jurisdicao'], 'verbose_name': 'Jurisdiction Alert', 'verbose_name_plural': 'Jurisdiction Alerts'},
        ),
        migrations.AddField(
            model_name='alertajurisdicao',
            name='advance_notice_days',
            field=models.PositiveIntegerField(default=30, help_text='Days before deadline to trigger advance notice'),
        ),
        migrations.AddField(
            model_name='alertajurisdicao',
            name='auto_calculate_next',
            field=models.BooleanField(default=True, help_text='Automatically calculate next deadline after completion'),
        ),
        migrations.AddField(
            model_name='alertajurisdicao',
            name='compliance_url',
            field=models.URLField(blank=True, help_text='URL to compliance information or portal'),
        ),
        migrations.AddField(
            model_name='alertajurisdicao',
            name='custom_recurrence_config',
            field=models.JSONField(default=dict, help_text='Custom configuration for complex recurrence patterns'),
        ),
        migrations.AddField(
            model_name='alertajurisdicao',
            name='deadline_type',
            field=models.CharField(choices=[('SINGLE', 'Single Deadline'), ('RECURRING', 'Recurring Deadline')], default='SINGLE', help_text='Type of deadline (single or recurring)', max_length=20),
        ),
        migrations.AddField(
            model_name='alertajurisdicao',
            name='last_completed',
            field=models.DateField(blank=True, help_text='Date when this alert was last completed', null=True),
        ),
        migrations.AddField(
            model_name='alertajurisdicao',
            name='next_deadline',
            field=models.DateField(blank=True, help_text='Next calculated deadline date', null=True),
        ),
        migrations.AddField(
            model_name='alertajurisdicao',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMIANNUAL', 'Semiannual'), ('ANNUAL', 'Annual'), ('BIENNIAL', 'Biennial'), ('CUSTOM', 'Custom Pattern')], help_text='Pattern for recurring deadlines', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alertajurisdicao',
            name='single_deadline',
            field=models.DateField(blank=True, help_text='Single deadline date (for non-recurring alerts)', null=True),
        ),
        migrations.AddField(
            model_name='alertajurisdicao',
            name='template_url',
            field=models.URLField(blank=True, help_text='URL to template or form for this alert'),
        ),
        migrations.AddField(
            model_name='alertajurisdicao',
            name='ubos_aplicaveis',
            field=models.ManyToManyField(blank=True, help_text='UBOs to which this alert applies', to='estruturas_app.ubo'),
        ),
        migrations.AlterField(
            model_name='alertajurisdicao',
            name='tipo_alerta',
            field=models.CharField(choices=[('TAX', 'Tax Obligation'), ('COMPLIANCE', 'Compliance Requirement'), ('REPORTING', 'Reporting Obligation'), ('DEADLINE', 'Important Deadline'), ('REGULATORY', 'Regulatory Change'), ('RENEWAL', 'License/Registration Renewal'), ('FILING', 'Required Filing')], help_text='Type of alert', max_length=20),
        ),
        migrations.AddIndex(
            model_name='alertajurisdicao',
            index=models.Index(fields=['jurisdicao', 'tipo_alerta'], name='estruturas__jurisdi_8047a9_idx'),
        ),
        migrations.AddIndex(
            model_name='alertajurisdicao',
            index=models.Index(fields=['next_deadline'], name='estruturas__next_de_bc5747_idx'),
        ),
        migrations.AddIndex(
            model_name='alertajurisdicao',
            index=models.Index(fields=['deadline_type'], name='estruturas__deadlin_5caa01_idx'),
        ),
        migrations.AddIndex(
            model_name='alertajurisdicao',
            index=models.Index(fields=['prioridade'], name='estruturas__priorid_a63968_idx'),
        ),
        migrations.AddIndex(
            model_name='alertajurisdicao',
            index=models.Index(fields=['ativo'], name='estruturas__ativo_3816b1_idx'),
        ),
        migrations.AddField(
            model_name='serviceactivity',
            name='service',
            field=models.ForeignKey(help_text='Service this activity belongs to', on_delete=django.db.models.deletion.CASCADE, to='estruturas_app.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='associated_product',
            field=models.ForeignKey(blank=True, help_text='Product this service is associated with (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='estruturas_app.product'),
        ),
        migrations.AddField(
            model_name='service',
            name='associated_structure',
            field=models.ForeignKey(blank=True, help_text='Legal Structure this service is associated with (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='estruturas_app.estrutura'),
        ),
        migrations.AddField(
            model_name='alertajurisdicao',
            name='service_connection',
            field=models.ForeignKey(blank=True, help_text='Associated service for this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estruturas_app.service'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['service', 'status'], name='estruturas__service_df363d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['start_date'], name='estruturas__start_d_cfb48d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['due_date'], name='estruturas__due_dat_6031ed_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['status'], name='estruturas__status_1f3f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['priority'], name='estruturas__priorit_eb7edd_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['responsible_person'], name='estruturas__respons_94a98c_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_type'], name='estruturas__service_39d419_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status'], name='estruturas__status_6e62fa_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['associated_product'], name='estruturas__associa_3dc502_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['associated_structure'], name='estruturas__associa_c0e3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['ativo'], name='estruturas__ativo_5771f2_idx'),
        ),
    ]
