# Generated by Django 4.2.7 on 2025-07-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estruturas_app', '0009_create_producthierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrutura',
            name='jurisdicao',
            field=models.CharField(
                choices=[
                    ('US', 'United States'),
                    ('BS', 'Bahamas'),
                    ('BR', 'Brazil'),
                    ('BZ', 'Belize'),
                    ('VG', 'British Virgin Islands'),
                    ('KY', 'Cayman Islands'),
                    ('PA', 'Panama'),
                ],
                default='US',
                help_text='Primary jurisdiction',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='estrutura',
            name='estado_us',
            field=models.CharField(
                blank=True,
                choices=[
                    ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'),
                    ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'),
                    ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'),
                    ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'),
                    ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'),
                    ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'),
                    ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'),
                    ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'),
                    ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'),
                    ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'),
                    ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'),
                    ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'),
                    ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia'),
                ],
                help_text='US State (only if jurisdiction is United States)',
                max_length=10,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='estrutura',
            name='estado_br',
            field=models.CharField(
                blank=True,
                choices=[
                    ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'),
                    ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'),
                    ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'),
                    ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'),
                    ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'),
                    ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'),
                    ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'),
                ],
                help_text='Brazilian State (only if jurisdiction is Brazil)',
                max_length=10,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='estrutura',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('TRUST', 'Trust'),
                    ('FOREIGN_TRUST', 'Foreign Trust'),
                    ('FUND', 'Fund'),
                    ('IBC', 'International Business Company'),
                    ('LLC_DISREGARDED', 'LLC Disregarded Entity'),
                    ('LLC_PARTNERSHIP', 'LLC Partnership'),
                    ('LLC_AS_CORP', 'LLC as a Corp'),
                    ('CORP', 'Corp'),
                    ('WYOMING_FOUNDATION', 'Wyoming Statutory Foundation'),
                ],
                help_text='Structure type',
                max_length=50
            ),
        ),
    ]
