# Generated by Django 4.2.7 on 2025-07-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estruturas_app', '0010_add_jurisdiction_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='configuracao',
        ),
    ]
