# Generated by Django 4.2.7 on 2025-07-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto', max_length=100)),
                ('complexidade_template', models.CharField(choices=[('BASIC', 'Basic Configuration'), ('INTERMEDIATE', 'Intermediate Configuration'), ('ADVANCED', 'Advanced Configuration'), ('EXPERT', 'Expert Configuration')], default='BASIC', help_text='Nível de complexidade', max_length=20)),
                ('descricao', models.TextField(help_text='Descrição detalhada do produto')),
                ('commercial_name', models.CharField(help_text='Nome comercial do produto (texto livre)', max_length=200)),
                ('master_agreement_url', models.URLField(help_text='URL para documento de Master Agreement')),
                ('custo_automatico', models.BooleanField(default=True, help_text='Se True, custo é calculado automaticamente das estruturas')),
                ('custo_manual', models.DecimalField(blank=True, decimal_places=2, help_text='Custo manual (usado quando custo_automatico=False)', max_digits=12, null=True)),
                ('tempo_total_implementacao', models.IntegerField(help_text='Tempo total de implementação em dias')),
                ('uso_count', models.IntegerField(default=0, help_text='Número de vezes que este produto foi usado')),
                ('publico_alvo', models.TextField(blank=True, help_text='Público-alvo do produto')),
                ('casos_uso', models.TextField(blank=True, help_text='Casos de uso comuns')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-uso_count', 'commercial_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order of this structure in the product hierarchy')),
                ('custom_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Custom cost for this structure in this product', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, help_text='Specific notes for this structure in this product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product that contains this structure', on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
                ('structure', models.ForeignKey(help_text='Legal structure included in the product', on_delete=django.db.models.deletion.CASCADE, to='corporate.structure')),
            ],
            options={
                'verbose_name': 'Product Hierarchy',
                'verbose_name_plural': 'Product Hierarchies',
                'ordering': ['product', 'order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='legal_structures',
            field=models.ManyToManyField(help_text='Legal structures included in this product', through='sales.ProductHierarchy', to='corporate.structure'),
        ),
        migrations.CreateModel(
            name='PersonalizedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto personalizado', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do produto personalizado')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived'), ('APPROVED', 'Approved')], default='DRAFT', help_text='Status atual do produto personalizado', max_length=20)),
                ('version_number', models.PositiveIntegerField(default=1, help_text='Número da versão (incrementado automaticamente)')),
                ('configuracao_personalizada', models.JSONField(blank=True, default=dict, help_text='Configurações específicas deste produto personalizado')),
                ('custom_configuration', models.JSONField(blank=True, help_text='Custom configuration for this personalized product', null=True)),
                ('custo_personalizado', models.DecimalField(blank=True, decimal_places=2, help_text='Custo personalizado (sobrescreve cálculo automático)', max_digits=12, null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações e notas específicas')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_product', models.ForeignKey(blank=True, help_text='Product base para este produto personalizado', null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
                ('base_structure', models.ForeignKey(blank=True, help_text='Legal Structure base para este produto personalizado', null=True, on_delete=django.db.models.deletion.CASCADE, to='corporate.structure')),
                ('parent_version', models.ForeignKey(blank=True, help_text='Versão anterior deste produto personalizado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_versions', to='sales.personalizedproduct')),
            ],
            options={
                'verbose_name': 'Personalized Product',
                'verbose_name_plural': 'Personalized Products',
                'ordering': ['-version_number', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='producthierarchy',
            index=models.Index(fields=['product', 'order'], name='sales_produ_product_c6dc71_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='producthierarchy',
            unique_together={('product', 'order'), ('product', 'structure')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['commercial_name'], name='sales_produ_commerc_f4c9c7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ativo'], name='sales_produ_ativo_c09c84_idx'),
        ),
        migrations.AddIndex(
            model_name='personalizedproduct',
            index=models.Index(fields=['base_product'], name='sales_perso_base_pr_26e697_idx'),
        ),
        migrations.AddIndex(
            model_name='personalizedproduct',
            index=models.Index(fields=['base_structure'], name='sales_perso_base_st_cc2f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='personalizedproduct',
            index=models.Index(fields=['status'], name='sales_perso_status_bc066c_idx'),
        ),
        migrations.AddIndex(
            model_name='personalizedproduct',
            index=models.Index(fields=['version_number'], name='sales_perso_version_24a9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='personalizedproduct',
            index=models.Index(fields=['ativo'], name='sales_perso_ativo_fa56c5_idx'),
        ),
    ]
